### ISSUE TITLE
Telegram ID's require BIGINT Integer type for administrator column.

### ISSUE THREAD

**Issue by pprovart** [Fumaz/EmojiCaptchaBot#1]
Telegram ID's are bigger than the type defined for Users and Administrators, so you will see an error when you type the /reload command and /verify command.

pony.orm.dbapiprovider.DataError: integer out of range or similar type messages.

This is because the Table is created with the administrator column defined as type integer [].

To fix this, find the Class definition for Chat ( starts line 205), then administrators, line 218.

BEFORE  
administrators = Required(IntArray, default=[])

add a qualifier to ensure the DB can handle the new BIGINT values when the Table is created.

AFTER
administrators = Required(IntArray, default=[], sql_type="bigint[]")

For Users the following modification need to be made to the Class definition for Users, from lines 94..

BEFORE
    id = PrimaryKey(int)
AFTER
    id = PrimaryKey(int, size=64)

**Comment by superantim** [comment]
> Telegram ID's are bigger than the type defined for Users and Administrators, so you will see an error when you type the /reload command and /verify command.
> 
> pony.orm.dbapiprovider.DataError: integer out of range or similar type messages.
> 
> This is because the Table is created with the administrator column defined as type integer [].
> 
> To fix this, find the Class definition for Chat ( starts line 205), then administrators, line 218.
> 
> BEFORE administrators = Required(IntArray, default=[])
> 
> add a qualifier to ensure the DB can handle the new BIGINT values when the Table is created.
> 
> AFTER administrators = Required(IntArray, default=[], sql_type="bigint[]")
> 
> For Users the following modification need to be made to the Class definition for Users, from lines 94..
> 
> BEFORE id = PrimaryKey(int) AFTER id = PrimaryKey(int, size=64)

i follow change from line 94 class User but have this error, how can i fix this
ERROR:pyrogram.dispatcher:Object User[5741591101] cannot be stored in the database. DataError: integer out of range

`ERROR:pyrogram.dispatcher:Object User[5741591101] cannot be stored in the database. DataError: integer out of range
Traceback (most recent call last):
  File "C:\Users\IPOS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyrogram\dispatcher.py", line 222, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\IPOS\Desktop\bot\BTKN_Bot\teleBot\bot\plugins\prehandler.py", line 15, in on_message
    message.db_user = await User.from_pyrogram(message)
  File "C:\Users\IPOS\Desktop\bot\BTKN_Bot\teleBot\db\models.py", line 158, in from_pyrogram
    db_user.tg = tg_user
  File "C:\Users\IPOS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pony\orm\core.py", line 481, in __exit__
    db_session._commit_or_rollback(exc_type, exc, tb)
  File "C:\Users\IPOS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pony\orm\core.py", line 495, in _commit_or_rollback
    commit()
  File "C:\Users\IPOS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pony\orm\core.py", line 386, in commit
    rollback_and_reraise(sys.exc_info())
  File "C:\Users\IPOS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pony\orm\core.py", line 375, in rollback_and_reraise
    reraise(*exc_info)
  File "C:\Users\IPOS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pony\utils\utils.py", line 95, in reraise
    try: raise exc.with_traceback(tb)
  File "C:\Users\IPOS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pony\orm\core.py", line 384, in commit
    cache.flush()
  File "C:\Users\IPOS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pony\orm\core.py", line 1901, in flush
    if obj is not None: obj._save_()
  File "C:\Users\IPOS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pony\orm\core.py", line 5437, in _save_
    if status == 'created': obj._save_created_()
  File "C:\Users\IPOS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pony\orm\core.py", line 5284, in _save_created_
    throw(UnexpectedError, 'Object %r cannot be stored in the database. %s: %s'
  File "C:\Users\IPOS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pony\utils\utils.py", line 106, in throw
    raise exc
    
pony.orm.core.UnexpectedError: Object User[5741591101] cannot be stored in the database. DataError: integer out of range`
